In [1]:
def convert_length():
    """
    Converts between meters and feet based on user input.
    """
    print("Choose conversion:")
    print("1. Meters to Feet")
    print("2. Feet to Meters")
    sub_choice = input("Enter 1 or 2: ")

    try:
        if sub_choice == "1":
            value_m = float(input("Enter distance in meters: "))
            feet = value_m * 3.28084  # 1 meter = 3.28084 feet
            print(f"{value_m} meters = {feet:.4f} feet")
        elif sub_choice == "2":
            value_ft = float(input("Enter distance in feet: "))
            meters = value_ft * 0.3048  # 1 foot = 0.3048 meters
            print(f"{value_ft} feet = {meters:.4f} meters")
        else:
            print("Invalid choice! Please enter 1 or 2.")
    except ValueError:
        print("Error: Please enter a valid numeric value.")

def convert_weight():
    """
    Converts between kilograms and pounds based on user input.
    """
    print("Choose conversion:")
    print("1. Kilograms to Pounds")
    print("2. Pounds to Kilograms")
    sub_choice = input("Enter 1 or 2: ")

    try:
        if sub_choice == "1":
            value_kg = float(input("Enter weight in kilograms: "))
            lbs = value_kg * 2.20462  # 1 kg = 2.20462 lbs
            print(f"{value_kg} kg = {lbs:.4f} lbs")
        elif sub_choice == "2":
            value_lbs = float(input("Enter weight in pounds: "))
            kg = value_lbs * 0.453592  # 1 lb = 0.453592 kg
            print(f"{value_lbs} lbs = {kg:.4f} kg")
        else:
            print("Invalid choice! Please enter 1 or 2.")
    except ValueError:
        print("Error: Please enter a valid numeric value.")

def convert_volume():
    """
    Converts between liters and gallons based on user input.
    """
    print("Choose conversion:")
    print("1. Liters to Gallons")
    print("2. Gallons to Liters")
    sub_choice = input("Enter 1 or 2: ")

    try:
        if sub_choice == "1":
            value_l = float(input("Enter volume in liters: "))
            gallons = value_l * 0.264172  # 1 liter = 0.264172 gallons
            print(f"{value_l} L = {gallons:.4f} gallons")
        elif sub_choice == "2":
            value_gal = float(input("Enter volume in gallons: "))
            liters = value_gal * 3.78541  # 1 gallon = 3.78541 liters
            print(f"{value_gal} gallons = {liters:.4f} liters")
        else:
            print("Invalid choice! Please enter 1 or 2.")
    except ValueError:
        print("Error: Please enter a valid numeric value.")

def unit_converter():
    """
    Prompts user to choose the type of conversion (length, weight, volume)
    and calls the corresponding function.
    """
    while True:
        print("\nUNIT CONVERTER")
        print("Choose the type of conversion:")
        print("1. Length (meters ↔ feet)")
        print("2. Weight (kilograms ↔ pounds)")
        print("3. Volume (liters ↔ gallons)")
        print("4. Exit")

        choice = input("Enter your choice (1-4): ")

        if choice == "1":
            convert_length()
        elif choice == "2":
            convert_weight()
        elif choice == "3":
            convert_volume()
        elif choice == "4":
            print("Exiting the Unit Converter. Goodbye!")
            break
        else:
            print("Invalid choice! Please enter a number between 1 and 4.")

# Run the converter
unit_converter()



UNIT CONVERTER
Choose the type of conversion:
1. Length (meters ↔ feet)
2. Weight (kilograms ↔ pounds)
3. Volume (liters ↔ gallons)
4. Exit
Enter your choice (1-4): 1
Choose conversion:
1. Meters to Feet
2. Feet to Meters
Enter 1 or 2: 2
Enter distance in feet: 1
1.0 feet = 0.3048 meters

UNIT CONVERTER
Choose the type of conversion:
1. Length (meters ↔ feet)
2. Weight (kilograms ↔ pounds)
3. Volume (liters ↔ gallons)
4. Exit
Enter your choice (1-4): 2
Choose conversion:
1. Kilograms to Pounds
2. Pounds to Kilograms
Enter 1 or 2: 2
Enter weight in pounds: 1
1.0 lbs = 0.4536 kg

UNIT CONVERTER
Choose the type of conversion:
1. Length (meters ↔ feet)
2. Weight (kilograms ↔ pounds)
3. Volume (liters ↔ gallons)
4. Exit
Enter your choice (1-4): 4
Exiting the Unit Converter. Goodbye!


In [2]:
def calculate_sum(lst):
    """Returns the sum of all elements in lst."""
    return sum(lst)

def calculate_average(lst):
    """Returns the average of all elements in lst."""
    return sum(lst) / len(lst) if lst else 0  # Prevent division by zero

def calculate_max(lst):
    """Returns the maximum element in lst."""
    return max(lst) if lst else None  # Prevent error on empty list

def calculate_min(lst):
    """Returns the minimum element in lst."""
    return min(lst) if lst else None  # Prevent error on empty list

def list_operations():
    """
    Prompts user for a list of numbers and an operation (sum, average, max, min).
    Performs the operation and prints the result.
    """
    while True:
        print("\nChoose the operation to perform on a list of numbers:")
        print("1. Sum")
        print("2. Average")
        print("3. Maximum")
        print("4. Minimum")
        print("5. Exit")

        choice = input("Enter 1, 2, 3, 4, or 5: ")

        if choice == "5":
            print("Exiting the program. Goodbye!")
            break  # Exit the loop if user chooses option 5

        numbers_str = input("Enter numbers separated by spaces: ")

        try:
            numbers = [float(x) for x in numbers_str.split()]
            if not numbers:
                print("Error: The list is empty. Please enter at least one number.")
                continue
        except ValueError:
            print("Error: One or more inputs could not be converted to a number.")
            continue

        if choice == "1":
            print(f"Sum = {calculate_sum(numbers)}")
        elif choice == "2":
            print(f"Average = {calculate_average(numbers):.2f}")
        elif choice == "3":
            print(f"Maximum = {calculate_max(numbers)}")
        elif choice == "4":
            print(f"Minimum = {calculate_min(numbers)}")
        else:
            print("Invalid choice! Please enter 1, 2, 3, 4, or 5.")

# Run the program
list_operations()



Choose the operation to perform on a list of numbers:
1. Sum
2. Average
3. Maximum
4. Minimum
5. Exit
Enter 1, 2, 3, 4, or 5: 2
Enter numbers separated by spaces: 1 2 3 4
Average = 2.50

Choose the operation to perform on a list of numbers:
1. Sum
2. Average
3. Maximum
4. Minimum
5. Exit
Enter 1, 2, 3, 4, or 5: 5
Exiting the program. Goodbye!


In [3]:
def extract_every_other(lst):
    """
    Returns a new list containing every other element from lst,
    starting with the first element (index 0).
    """
    return lst[::2]

def get_sublist(lst, start, end):
    """
    Returns a sublist from index 'start' to 'end' (inclusive).
    """
    return lst[start:end+1]

def reverse_list(lst):
    """
    Returns a reversed version of lst using slicing.
    """
    return lst[::-1]

def remove_first_last(lst):
    """
    Removes the first and last elements from lst and returns the resulting sublist.
    """
    return lst[1:-1] if len(lst) > 2 else []  # Prevents errors for very short lists

def get_first_n(lst, n):
    """
    Returns the first n elements of lst.
    """
    return lst[:n]

def get_last_n(lst, n):
    """
    Returns the last n elements of lst using slicing.
    """
    return lst[-n:]

def reverse_skip(lst):
    """
    Returns a new list containing every second element in reverse order,
    starting from the second-to-last element.
    """
    return lst[-2::-2]

def list_operations():
    """
    Interactive program for users to apply different list operations.
    """
    while True:
        print("\nChoose a list operation:")
        print("1. Extract Every Other Element")
        print("2. Get Sublist (start to end)")
        print("3. Reverse List")
        print("4. Remove First and Last Element")
        print("5. Get First N Elements")
        print("6. Get Last N Elements")
        print("7. Reverse and Skip Every Other")
        print("8. Exit")

        choice = input("Enter your choice (1-8): ")

        if choice == "8":
            print("Exiting the program. Goodbye!")
            break

        numbers_str = input("Enter a list of numbers separated by spaces: ")

        try:
            numbers = [float(x) for x in numbers_str.split()]
            if not numbers:
                print("Error: The list is empty. Please enter at least one number.")
                continue
        except ValueError:
            print("Error: One or more inputs could not be converted to a number.")
            continue

        if choice == "1":
            print("Result:", extract_every_other(numbers))
        elif choice == "2":
            start = int(input("Enter start index: "))
            end = int(input("Enter end index: "))
            print("Result:", get_sublist(numbers, start, end))
        elif choice == "3":
            print("Result:", reverse_list(numbers))
        elif choice == "4":
            print("Result:", remove_first_last(numbers))
        elif choice == "5":
            n = int(input("Enter number of elements to extract: "))
            print("Result:", get_first_n(numbers, n))
        elif choice == "6":
            n = int(input("Enter number of elements from the end: "))
            print("Result:", get_last_n(numbers, n))
        elif choice == "7":
            print("Result:", reverse_skip(numbers))
        else:
            print("Invalid choice! Please enter a number between 1 and 8.")

# Run the program
list_operations()



Choose a list operation:
1. Extract Every Other Element
2. Get Sublist (start to end)
3. Reverse List
4. Remove First and Last Element
5. Get First N Elements
6. Get Last N Elements
7. Reverse and Skip Every Other
8. Exit
Enter your choice (1-8): 1
Enter a list of numbers separated by spaces: 3
Result: [3.0]

Choose a list operation:
1. Extract Every Other Element
2. Get Sublist (start to end)
3. Reverse List
4. Remove First and Last Element
5. Get First N Elements
6. Get Last N Elements
7. Reverse and Skip Every Other
8. Exit
Enter your choice (1-8): 8
Exiting the program. Goodbye!


In [4]:
def flatten(lst):
    """
    Flattens a shallow (1-level) nested list into a single list.
    Assumes each element in lst is either an item or a sub-list.
    """
    flat_list = []
    for item in lst:
        if isinstance(item, list):
            flat_list.extend(item)
        else:
            flat_list.append(item)
    return flat_list

def access_nested_element(lst, indices):
    """
    Given a list of indices, traverses the nested list accordingly
    and returns the specified element.
    """
    try:
        element = lst
        for idx in indices:
            element = element[idx]
        return element
    except (IndexError, TypeError):
        return "Invalid index path!"

def sum_nested(lst):
    """
    Returns the sum of all numeric elements in a nested list, regardless of depth.
    """
    total = 0
    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)
        else:
            total += item
    return total

def remove_element(lst, elem):
    """
    Removes all occurrences of 'elem' from the nested list lst (any depth).
    Modifies and returns the original list structure, but with those elements removed.
    """
    result = []
    for item in lst:
        if isinstance(item, list):
            filtered = remove_element(item, elem)
            if filtered:
                result.append(filtered)
        else:
            if item != elem:
                result.append(item)
    return result

def find_max(lst):
    """
    Finds the maximum element in a nested list, regardless of depth.
    """
    current_max = None
    for item in lst:
        if isinstance(item, list):
            sub_max = find_max(item)
            if current_max is None or (sub_max is not None and sub_max > current_max):
                current_max = sub_max
        else:
            if current_max is None or item > current_max:
                current_max = item
    return current_max

def count_occurrences(lst, elem):
    """
    Counts how many times 'elem' appears in the nested list 'lst', at any depth.
    """
    count = 0
    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)
        else:
            if item == elem:
                count += 1
    return count

def deep_flatten(lst):
    """
    Recursively flattens a deeply nested list into a single list.
    """
    result = []
    for item in lst:
        if isinstance(item, list):
            result.extend(deep_flatten(item))
        else:
            result.append(item)
    return result

def average_nested(lst):
    """
    Calculates the average of all numeric elements in the nested list 'lst' (any depth).
    """
    flat = deep_flatten(lst)
    return sum(flat) / len(flat) if flat else "No numeric values to average."

def nested_list_operations():
    """
    Interactive program to allow users to perform nested list operations.
    """
    while True:
        print("\nChoose a nested list operation:")
        print("1. Flatten (1-level nested list)")
        print("2. Access Nested Element")
        print("3. Sum of All Numbers in Nested List")
        print("4. Remove Specific Element from Nested List")
        print("5. Find Maximum Element in Nested List")
        print("6. Count Occurrences of an Element")
        print("7. Deep Flatten (Any Level)")
        print("8. Average of Numbers in Nested List")
        print("9. Exit")

        choice = input("Enter your choice (1-9): ")

        if choice == "9":
            print("Exiting the program. Goodbye!")
            break

        try:
            nested_list = eval(input("Enter a nested list (use proper Python syntax): "))
            if not isinstance(nested_list, list):
                print("Error: You must enter a valid list.")
                continue
        except Exception as e:
            print(f"Invalid input: {e}")
            continue

        if choice == "1":
            print("Result:", flatten(nested_list))
        elif choice == "2":
            indices_str = input("Enter indices separated by spaces (e.g., '1 0 2'): ")
            indices = [int(x) for x in indices_str.split()]
            print("Result:", access_nested_element(nested_list, indices))
        elif choice == "3":
            print("Result:", sum_nested(nested_list))
        elif choice == "4":
            elem = eval(input("Enter the element to remove: "))
            print("Result:", remove_element(nested_list, elem))
        elif choice == "5":
            print("Result:", find_max(nested_list))
        elif choice == "6":
            elem = eval(input("Enter the element to count: "))
            print("Result:", count_occurrences(nested_list, elem))
        elif choice == "7":
            print("Result:", deep_flatten(nested_list))
        elif choice == "8":
            print("Result:", average_nested(nested_list))
        else:
            print("Invalid choice! Please enter a number between 1 and 9.")

# Run the program
nested_list_operations()



Choose a nested list operation:
1. Flatten (1-level nested list)
2. Access Nested Element
3. Sum of All Numbers in Nested List
4. Remove Specific Element from Nested List
5. Find Maximum Element in Nested List
6. Count Occurrences of an Element
7. Deep Flatten (Any Level)
8. Average of Numbers in Nested List
9. Exit
Enter your choice (1-9): 1
Enter a nested list (use proper Python syntax): [[1,2,3,4]]
Result: [1, 2, 3, 4]

Choose a nested list operation:
1. Flatten (1-level nested list)
2. Access Nested Element
3. Sum of All Numbers in Nested List
4. Remove Specific Element from Nested List
5. Find Maximum Element in Nested List
6. Count Occurrences of an Element
7. Deep Flatten (Any Level)
8. Average of Numbers in Nested List
9. Exit
Enter your choice (1-9): 1
Enter a nested list (use proper Python syntax): [9,8,7,6]
Result: [9, 8, 7, 6]

Choose a nested list operation:
1. Flatten (1-level nested list)
2. Access Nested Element
3. Sum of All Numbers in Nested List
4. Remove Specific E

In [5]:
import numpy as np

# 1) Creating arrays with zeros, ones, empty, etc.
arr_empty = np.empty((2,2))
arr_ones = np.ones((4,2))
arr_full = np.full((3,3), 9)

print("Empty 2x2:\n", arr_empty)
print("\nOnes 4x2:\n", arr_ones)
print("\nFull 3x3 with 9:\n", arr_full)

# 2) Using arange and reshape
arr_range = np.arange(10, 50)
matrix_3x3 = np.arange(9).reshape(3,3)
identity_3x3 = np.eye(3)

print("\nArray from 10 to 49:\n", arr_range)
print("\n3x3 matrix 0..8:\n", matrix_3x3)
print("\n3x3 identity:\n", identity_3x3)

# 3) Random arrays
random_arr_30 = np.random.random(30)
mean_val = random_arr_30.mean()
print("\nRandom array of size 30, mean value:", mean_val)

arr_10x10 = np.random.random((10,10))
min_val = arr_10x10.min()
max_val = arr_10x10.max()
print("\n10x10 random array => min:", min_val, ", max:", max_val)

# 4) Zero array replaced with 1 in the 5th element
arr_10 = np.zeros(10, dtype=int)
arr_10[4] = 1
print("\nZero array with 5th element replaced by 1:", arr_10)

# 5) Reverse an array
arr_to_reverse = np.array([1,2,0,0,4,0])
reversed_arr = arr_to_reverse[::-1]
print("\nOriginal:", arr_to_reverse, "=> Reversed:", reversed_arr)

# 6) 2D array with 1s on the border, 0 inside
n = 5
bordered_arr = np.zeros((n,n), dtype=int)
bordered_arr[0, :] = 1
bordered_arr[-1, :] = 1
bordered_arr[:, 0] = 1
bordered_arr[:, -1] = 1
print("\n5x5 array with border of 1s:\n", bordered_arr)

# 7) 8x8 checkerboard
checkerboard = np.zeros((8,8), dtype=int)
checkerboard[::2, 1::2] = 1
checkerboard[1::2, ::2] = 1
print("\nCheckerboard 8x8:\n", checkerboard)

Empty 2x2:
 [[1.92132199e-316 0.00000000e+000]
 [1.93115874e-316 1.93115874e-316]]

Ones 4x2:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Full 3x3 with 9:
 [[9 9 9]
 [9 9 9]
 [9 9 9]]

Array from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

3x3 matrix 0..8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

3x3 identity:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Random array of size 30, mean value: 0.537229318054988

10x10 random array => min: 0.013073553770901913 , max: 0.9945017372263506

Zero array with 5th element replaced by 1: [0 0 0 0 1 0 0 0 0 0]

Original: [1 2 0 0 4 0] => Reversed: [0 4 0 0 2 1]

5x5 array with border of 1s:
 [[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]

Checkerboard 8x8:
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### **Array and Matrix Operations**

In [6]:
# Some sample arrays
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

# Element-wise addition
x_plus_y = x + y
print("x + y =\n", x_plus_y)

# Subtraction
x_minus_y = x - y
print("\nx - y =\n", x_minus_y)

# Multiply x by 3
x_times_3 = x * 3
print("\nx * 3 =\n", x_times_3)

# Square each element
x_squared = x ** 2
print("\nx squared =\n", x_squared)

# Dot products
dot_vw = np.dot(v, w)
dot_xv = x.dot(v)
dot_xy = np.dot(x, y)
print("\nv · w =", dot_vw)
print("x · v =", dot_xv)
print("x · y =\n", dot_xy)

# Concatenate x and y along rows
concat_xy_rows = np.concatenate((x, y), axis=0)
print("\nConcatenate x,y along rows:\n", concat_xy_rows)

# Concatenate v and w along columns (first reshape them)
v_col = v.reshape(-1,1)
w_col = w.reshape(-1,1)
concat_vw_cols = np.concatenate((v_col, w_col), axis=1)
print("\nConcatenate v,w along columns:\n", concat_vw_cols)

# Attempt to concatenate x and v (will fail if shapes don't match)
try:
    concat_xv_fail = np.concatenate((x, v), axis=0)
    print("\nConcatenate x,v (axis=0):\n", concat_xv_fail)
except ValueError as e:
    print("\nError concatenating x and v:", e)

# Fix: reshape v
v_reshaped = v.reshape(1,2)
concat_xv_fixed = np.concatenate((x, v_reshaped), axis=0)
print("\nFix by reshaping v to (1,2):\n", concat_xv_fixed)

x + y =
 [[ 6  8]
 [10 13]]

x - y =
 [[-4 -4]
 [-4 -3]]

x * 3 =
 [[ 3  6]
 [ 9 15]]

x squared =
 [[ 1  4]
 [ 9 25]]

v · w = 219
x · v = [29 77]
x · y =
 [[19 22]
 [50 58]]

Concatenate x,y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenate v,w along columns:
 [[ 9 11]
 [10 12]]

Error concatenating x and v: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

Fix by reshaping v to (1,2):
 [[ 1  2]
 [ 3  5]
 [ 9 10]]


### **Matrix Inverse & Checking Commutativity**

In [7]:
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

# A inverse
A_inv = np.linalg.inv(A)
AA_inv = A @ A_inv
print("A @ A_inv =\n", AA_inv)
print("Is close to identity?", np.allclose(AA_inv, np.eye(2)))

# Commutativity
AB = A @ B
BA = B @ A
print("\nAB =\n", AB)
print("\nBA =\n", BA)
print("\nAre AB and BA equal?", np.array_equal(AB, BA))

# (AB)^T vs B^T A^T
AB_t = (A @ B).T
BT_AT = B.T @ A.T
print("\n(AB)^T:\n", AB_t)
print("\nB^T A^T:\n", BT_AT)
print("\nAre they close?", np.allclose(AB_t, BT_AT))

A @ A_inv =
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
Is close to identity? True

AB =
 [[23 13]
 [51 29]]

BA =
 [[36 44]
 [13 16]]

Are AB and BA equal? False

(AB)^T:
 [[23 51]
 [13 29]]

B^T A^T:
 [[23 51]
 [13 29]]

Are they close? True


### **Solving a System of Equations**
We have the system:
\begin{cases}
2x - 3y + z = -1 \
x - y + 2z = -3 \
3x + y - z = 9
\end{cases}

In [8]:
A_sys = np.array([
    [ 2, -3,  1],
    [ 1, -1,  2],
    [ 3,  1, -1]
], dtype=float)

B_sys = np.array([-1, -3, 9], dtype=float)

A_inv_sys = np.linalg.inv(A_sys)
X = A_inv_sys @ B_sys
print("Solution via inverse:", X)

# Alternatively:
X_alt = np.linalg.solve(A_sys, B_sys)
print("Solution via np.linalg.solve:", X_alt)

Solution via inverse: [ 2.  1. -2.]
Solution via np.linalg.solve: [ 2.  1. -2.]


# **Performance Comparison: NumPy vs Python Lists**
Below is optional code that compares the speed of basic operations. **Uncomment** to run and measure.


In [10]:
import time

size = 1_000_000

# Python lists
py_list1 = list(range(size))
py_list2 = list(range(size))

# Addition
start = time.time()
py_sum = [py_list1[i] + py_list2[i] for i in range(size)]
end = time.time()
py_time_add = end - start
print(f"Python list addition took {py_time_add:.5f} seconds.")

# NumPy arrays
np_arr1 = np.arange(size)
np_arr2 = np.arange(size)

start = time.time()
np_sum = np_arr1 + np_arr2
end = time.time()
np_time_add = end - start
print(f"NumPy array addition took {np_time_add:.5f} seconds.")

# Element-wise multiplication
start = time.time()
py_mul = [py_list1[i] * py_list2[i] for i in range(size)]
end = time.time()
py_time_mul = end - start
print(f"Python list multiplication took {py_time_mul:.5f} seconds.")

start = time.time()
np_mul = np_arr1 * np_arr2
end = time.time()
np_time_mul = end - start
print(f"NumPy array multiplication took {np_time_mul:.5f} seconds.")

# Dot product
start = time.time()
py_dot = sum(py_list1[i] * py_list2[i] for i in range(size))
end = time.time()
py_time_dot = end - start
print(f"Python list dot product took {py_time_dot:.5f} seconds.")

start = time.time()
np_dot = np.dot(np_arr1, np_arr2)
end = time.time()
np_time_dot = end - start
print(f"NumPy array dot product took {np_time_dot:.5f} seconds.")

# Matrix multiplication example (1000x1000)
mat_size = 1000
py_mat1 = [[1]*mat_size for _ in range(mat_size)]
py_mat2 = [[2]*mat_size for _ in range(mat_size)]

start = time.time()
py_mat_result = [[0]*mat_size for _ in range(mat_size)]
for i in range(mat_size):
    for j in range(mat_size):
        s = 0
        for k in range(mat_size):
            s += py_mat1[i][k] * py_mat2[k][j]
        py_mat_result[i][j] = s
end = time.time()
py_mat_time = end - start
print(f"\nPython list-based 1000x1000 matrix multiplication took {py_mat_time:.5f} seconds.")

np_mat1 = np.ones((mat_size, mat_size), dtype=int)
np_mat2 = np.full((mat_size, mat_size), 2, dtype=int)

start = time.time()
np_mat_result = np_mat1.dot(np_mat2)
end = time.time()
np_np_time = end - start
print(f"NumPy 1000x1000 matrix multiplication took {np_np_time:.5f} seconds.")

Python list addition took 0.12939 seconds.
NumPy array addition took 0.00661 seconds.
Python list multiplication took 0.09123 seconds.
NumPy array multiplication took 0.00826 seconds.
Python list dot product took 0.09429 seconds.
NumPy array dot product took 0.03685 seconds.

Python list-based 1000x1000 matrix multiplication took 270.03322 seconds.
NumPy 1000x1000 matrix multiplication took 4.82650 seconds.


---
## **End of Worksheet 0 Solutions**
You can adapt or extend these code snippets as needed.

> **Remember**: Understanding each approach is crucial for mastery!